### ISSUE TITLE
issues with bg using color

### ISSUE THREAD

**Issue by The-Code-Monkey** [spicy-ui/styled-system#2]
If bg is now related to the background property instead of the background-color property. I believe it should have its own key within the theme something like backgrounds and if it cant find the value in there check the colors as a backup scale, as background isnt always a color it could be other things if your trying to stick to the css spec closer.

Edit: I'm going to be doing this in my fork at some point feel free to cherry pick my commit into yours if you think this is a good thing. My version will also have some things that are either specific to my needs or I feel work better for me.

**Comment by South-Paw** [comment]
Thanks for your suggestion however I'd prefer to keep it as similar to the original styled-system and theme UI spec as possible.

If you'd like to change the `background` property to use a different scale, you can duplicate the [background parser](https://github.com/spicy-ui/styled-system/blob/master/src/parsers/background.ts) and adjust the [scale key](https://github.com/spicy-ui/styled-system/blob/master/src/parsers/background.ts#L25) to be whatever you'd like it to be - then use just replace usages of the `@spicy-ui/styled-system` background parser with your custom background parser.
